name: melos_example

packages:
  - apps/**
  - packages/**

scripts:
  analyze:
    exec: dart analyze .

  format:
    exec: dart format .

  verify_formatting:
    exec: dart format --output=none --set-exit-if-changed .

  clean:
    exec: flutter clean

  test:
    exec: flutter test